services:
  - type: web
    name: ai-cctv-backend
    buildCommand: |
      pip install -r requirements.txt
      cd cctv-dashboard && npm install && npm run build
      mkdir -p app/static
      cp -r dist/* ../app/static/
    autoDeploy: true
    region: oregon
    startCommand: gunicorn main:app --chdir app