services:
  - type: web
    name: ai-cctv-backend
    buildCommand: |
      pip install -r requirements.txt
      cd cctv-dashboard && npm install && npm run build
      mkdir -p app/static
      cp -r dist/* ../app/static/
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    region: oregon
